name: CI-Backend  # Name of the workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      -main
    paths: -'CityVoxWeb/**'  # Specify the paths to trigger this workflow
    
env:
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3  # Sets up .NET Core
      with:
        dotnet-version: '6.0.x'  # Specify your .NET Core version

    - name: Restore dependencies
      run: dotnet restore CityVoxWeb/CityVoxWeb.sln # Restore NuGet packages

    - name: Build
      run: dotnet build --no-restore CityVoxWeb/CityVoxWeb.sln 

    - name: Publish
      run: dotnet publish CityVoxWeb/CityVoxWeb.API/CityVoxWeb.API.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_PROJECT_TOKEN }}

  deploy:
   runs-on: windows-latest
   needs: build
   environment:
     name: 'Production'
     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

   steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CityVox'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A13E53351BCD420BA2A47CC5CF3EDEA9 }}
          package: .
