name: CI-Backend  # Name of the workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - SofiaCallWebCrawler
    paths: -'CityVoxWeb/**'  # Specify the paths to trigger this workflow
  pull_request:
    branches: [ main ]
    paths: -'CityVoxWeb/**'

jobs:
  build:
    runs-on: ubuntu-latest  # Using a Windows runner for .NET

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3  # Sets up .NET Core
      with:
        dotnet-version: '6.0.x'  # Specify your .NET Core version

    - name: Restore dependencies
      run: dotnet restore CityVoxWeb/CityVoxWeb.sln # Restore NuGet packages

    - name: Build
      run: dotnet build --no-restore CityVoxWeb/CityVoxWeb.sln 

    - name: Publish
      run: dotnet publish CityVoxWeb/CityVoxWeb.sln -c Release -o out
