name: Build and deploy ReactJS+Vite app to Azure Web App - CityVoxClient

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          cd CityVoxClient
          npm install

      - name: Build the Vite project
        run: |
          cd CityVoxClient
          npm run build

      - name: Zip artifact for deployment
        run: |
          cd CityVoxClient
          zip -r ../release.zip ./dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: react-vite-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: react-vite-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CityVoxClient'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0BE74ECB0CBA413D8CA7E5932DE87EB6 }}
